### PR TITLE
Phumudzo/resizable panel

### PR DESCRIPTION
**Pull request by nthangeniphumudzo**
Hi @IvanIlyichev . I am trying to address this [issue](https://github.com/shesha-io/shesha-framework/issues/502) , but avoiding point number 6.  I have made use of "SizableColumns" to have uniform signature on resizable. Please kindly review and advise.

### CODE REVIEW

**Review by IvanIlyichev — CHANGES_REQUESTED** [review]
Hi @nthangeniphumudzo. The code is not compilable

**Review by IvanIlyichev — CHANGES_REQUESTED** [review]
Hi @nthangeniphumudzo. Please make following changes/fixes:
1. Increase initial width of the properties panel, it should be approximately the same as before your changes
2. Hide the `Data` tab when it's not available
3. SidebarContainer is used for datatables too and currently it's broken
4. Sizeable panel sometimes doesn't react on panel collapsing. Steps to reproduce: load the designer page, resize properties panel and then click on the collapse button

**Comment by nthangeniphumudzo** [comment]
Hi @IvanIlyichev . I have adjusted the code , but point 1. I didn't increase the initial width of the panel because there was a request to shrink them and reduce the panel padding and space between components. I have also fixed the direction of the panel icons. Please review and advise.

**Review by IvanIlyichev — CHANGES_REQUESTED** [review]
Hi @nthangeniphumudzo.
Please test it thoroughly. I found following problems:
1. drag&drop of components from the toolbox doesn't work
2. Resize of the left panel at some point affects right panel
3. Collapse of one panel resets a size of another panel
4. Resizing is slow

**Review by IvanIlyichev — CHANGES_REQUESTED** [review]
Hi @nthangeniphumudzo. Please make the following changes:
1. disable resizing when panel is collapsed 
2. reduce width of the panel when collapsed, it should contain only the expand button without white space

**Review by IvanIlyichev — APPROVED** [review]

**Pull request merged**
