### PR TITLE
James/e/1878autocomplete

### PR DESCRIPTION
**Pull request by James-Baloyi**
#1878

### CODE REVIEW

**Review by IvanIlyichev — CHANGES_REQUESTED** [review]
Hi @James-Baloyi. Border style should work taking in account the **Hide border** and it should be implemented by the same way for all components affected by your changes. The **Hide border** should be above other border settings which tweak border style and these settings should be hidden when the **hide border** is switched on. Please review other components too

**Comment by James-Baloyi** [comment]
@IvanIlyichev the requested changes have been committed

**Review by IvanIlyichev — CHANGES_REQUESTED** [review]
Hi @James-Baloyi. 
1. Border radius is still visible when the Hide border is switched on. 
2. Please revert back **variant** property, all components should behave by the same way

**Comment by James-Baloyi** [comment]
@IvanIlyichev the reason border radius is still visible is the same as the one here https://github.com/shesha-io/shesha-framework/pull/1927

I've added the default border radius and reverted variant to the previous implementation.

**Pull request merged**
