### PR TITLE
richtext editr placeholder fix

### LINKED ISSUE #1656: RichTextEditor component displays value on top of placeholder text when rendered in a edit dialog
**Steps to reproduce the behavior:**
1. Go to 'https://function-adminportal-test.shesha.dev/dynamic/TestModule/testRich-table'
2. Click on 'edit' pencil of any record on the table
3. Upon displaying the dialog, check the value displayed on the richTextEditor component
4. Actual Results: The value is not clearly visible due to the placeholder text showing while there's a value

**Expected behavior**
If a placeholder is specified, upon rendering, if the component has a value, the placeholder should not show. The placeholder only shows when the component is empty. See details view: https://function-adminportal-test.shesha.dev/dynamic/Boxfusion.SheshaFunctionalTests.Common/employee-text-details?id=da78f30f-2afe-4f94-9c8b-03f4f3978ead

image

### PR DESCRIPTION
**Pull request by James-Baloyi**
#1656

### CODE REVIEW

**Review by IvanIlyichev — APPROVED** [review]
Hi @James-Baloyi . Please move placeholder recalculation to existing memoized `fullConfig` and add `state?.content` to the dependencies

**Comment by James-Baloyi** [comment]
Hi @IvanIlyichev I've updated the ticket

**Review by IvanIlyichev — CHANGES_REQUESTED** [review]
@James-Baloyi placeholder should be a part of the fullConfig. State update inside the useMemo is 100% incorrect. The idea was to decrease number of unneeded re-renders

**Comment by IvanIlyichev** [comment]
@James-Baloyi I've made a fix myself and pushed it. Please test your changes before you make a PR

**Pull request closed without merging**
