### PR TITLE
james/en/2307

### PR DESCRIPTION
**Pull request by James-Baloyi**
#2307 

There were issues with spacing between the drag handler and selected icon, and the button component capturing click and drag events.

### CODE REVIEW

**Review by IvanIlyichev — CHANGES_REQUESTED** [review]
Hi @James-Baloyi. Drag handle must not go beyond the current element (see attached image). Please review styles of the list editor, it's related not only to this PR, it's a results of your previous changes. 
image

**Comment by James-Baloyi** [comment]
@IvanIlyichev the issue has been addressed

**Review by IvanIlyichev — CHANGES_REQUESTED** [review]
Hi @James-Baloyi. The markup is still wrong. You are trying to align items using relative values (%) and absolute (px) at the same time. If we still use drag indicator it should be centered properly and dragging area shouldn't exceed the container. 
dragHandle - if you use absolute positioning, then set size using left/right/top/bottom properties
dragIcon cannot be centered using absolute values

**Review by IvanIlyichev — CHANGES_REQUESTED** [review]
@James-Baloyi. Now **sha-drag-handle** overlaps **sha-list-item-controls**

**Comment by James-Baloyi** [comment]
@IvanIlyichev I've reduced its footprint so it doesn't overlap with the controls, however, it previously was aligned below them so it would not affect their functionality.

**Comment by IvanIlyichev** [comment]
@James-Baloyi yes, the alignment was incorrect even before this PR

**Review by IvanIlyichev — APPROVED** [review]

**Pull request merged**
